---
# configuration file template
google_static_map: # google cloud api key
  api_key: 
what3words: # what3words api key
  api_key: 
twitter_auth: # twitter developer credentials
  api_key: 
  api_secret_key: 
  access_token: 
  secret_access_token: 
  bearer_token: 